# Configuration for GHES instances
ghes_instances:
  - name: 'ghes-qa'
    api_url: 'https://api.ghes-qa.example.com/api/v3' 
    auth_var: 'GHES_API_TOKEN_QA'  
  - name: 'ghes-prod'
    api_url: 'https://api.ghes-prod.example.com/api/v3'
    auth_var: 'GHES_API_TOKEN_PROD'

# GitHub Enterprise Cloud configuration for license management
ghec:
  name: 'ghec-instance'
  api_url: 'https://api.github.com'
  auth_var: 'GH_ENTERPRISE_TOKEN_CLOUD'
